.travis.yml
In the future we should probably change this to use relative paths, but this should fix the build issue
=> remove extra TwitchLib from dotnet build path

TwitchLib.Client/TwitchClient.cs
=> Log warning messages instead of throwing exceptions for OnBeingHosted event and GetChannelModerators method.

TwitchLib.Client/Extensions/GetChannelModeratorsExt.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
The big (and controversial?) change here is that this was removed because of the nature of extensions:
```csharp
if (OnModeratorsReceived == null)
Log("[GetChannelModerators] You are not listening to OnModeratorsReceived. The response to this message will not be handled.");
```
This was originally an exception, but because exceptions are not ideal, it was moved to a log message. Now, because extension methods don't normally have access to events, we also can't do the above code. I'm not entirely convinced the above code is absolutely necessary tbh. Additionally, the logging needs work, and that was kind of half-assed.
The goal of this PR is to move GetChannelModerators (ie "/mods") command to an extension like the other commands.
discuss
=> GetChannelModerators method moved to extension.

TwitchLib.Client/Exceptions/FailureToReceiveJoinConfirmationException.cs, TwitchLib.Client/TwitchClient.cs
- detect suspended channel and raise OnFailureToReceiveJoinConfirmation event
- remove channel from awaiting joins
- resume join queue
Related: #43
=> Detect suspended channel, resume join queue. Related to #43

TwitchLib.Client/Extensions/EventInvocationExt.cs, TwitchLib.Client/Models/ChatMessage.cs, TwitchLib.Client/TwitchClient.cs
- Exposes ChatMessage Id property
- UnAccountedFor event no longer fires in OnMessageReceived
- Removes suspended channels from joinedchannel list
=> Expose ChatMessage.Id and some smaller fixes. Related to #44

TwitchLib.Client/TwitchClient.cs
The `OnFailureToReceiveJoinConfirmation` event would never fire because `_joinTimer` is always stopped after it first elapses.
Also need to reset `_currentlyJoiningChannels` to false and call `QueuingJoinCheck()` here so the client is able to join new channels afterwards.
=> Fix OnFailureToReceiveJoinConfirmation event

TwitchLib.Client/Extensions/BanUserExt.cs, TwitchLib.Client/Extensions/RaidExt.cs, TwitchLib.Client/Extensions/TimeoutUserExt.cs, TwitchLib.Client/Extensions/UnbanUserExt.cs
- TimeoutUser doesn't allow not specifying a channel
- UnbanUser doesn't allow not specifying a channel
- BanUser doesn't allow not specifying a channel
- Raid now allows specifying a channel via string
=> Extension cleanup

TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client.Models/WhisperMessage.cs
Previously the EmoteSet was created before the message was parsed, meaning _emoteSetStorage would always be null, resulting in the EmoteSet being empty, which then again results in the EmoteSet having "EmoteSet.Emotes.Count" being 0.
This is a fix for #405 https://github.com/TwitchLib/TwitchLib/issues/405 
This does raise a question: Why is the instance of EmoteSet not being created in the switch Case, just like in the WhisperMessage? This seems to work just fine (see commit).
=> Emote set count zero fix

TwitchLib.Client/TwitchClient.cs
Roomstate fix:
- This fix allows the client to correctly detect when it joins a mod only room
- ROOMSTATE fires everytime a client joins a room/channel, as well as when a mode is toggled.
- When a mode is enabled (ie subonly, emoteonly, r9k, slow, etc), TAGS includes 2 keyvaluepairs. The room-id its for, as well as the mode being toggled (subonly, emoteonly, etc)
- When a client joins a room, all tags are included (which is more than 2).
Related to: #78
=> Fixes roomstate bug preventing join confirmation for some rooms

TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
Updated the Events in the Interface to match the ones in the TwitchClient Class.
OnRitualNewChatter was getting triggered and was not set as an event and made public through the interface.
All Events that were added to the interface are actually triggered somewhere in the class and are used.
I tried to respect the way the comments for the interface were made.
=> Add TwitchClient Events to Interface

TwitchLib.Client/Events/OnRaidNotificationArgs.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs, TwitchLib.Client/TwitchClient.cs
Not much to detail as far as changes.
The `OnRaidNotificationArgs` class had a property named `RaidNotificaiton`.  Corrected that spelling to `RaidNotification`.  All builds succeed and tests pass.
=> Fixed misspelled RaidNotification argument of OnRaidNotificationArgs

TwitchLib.Client/TwitchClient.cs
Clears joined channels when calling Connect()
Issue occurs when the library gets disconnected from a network issue and a new connection is established. Because the library didn't know it was disconnected it still thinks it's joined to the channels it was previously in. Unless you use the force join flag when calling the join channel function all calls to join channels you were previously in will be ignored because it thinks you're still in them.
=> Clear joined channels on connect

TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
I've seen this sort of ask show up in Discord a few times. This allows you to initialize the client with a list of channels. This means you don't need any special logic in `OnConnected` event to join additional channels.
=> adds ability to initialize client with multiple channels

TwitchLib.Client/TwitchClient.cs
This typo propagates [to the docs](https://swiftyspiffy.com/TwitchLib/Client/class_twitch_lib_1_1_client_1_1_twitch_client.html).
=> Fixes a typo (conneciton -> connection)

TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client.Models/TwitchLibMessage.cs, TwitchLib.Client.Models/WhisperMessage.cs
I've noticed that `WhisperMessage` does not have the `RawIrcMessage` field like `ChatMessage` does, and had a quick check in the code why that might be. Trying it out real quick showed that there doesn't seem to be anything fundamentally different between chat messages and whisper messages.
This pull request attempts to eliminate that discrepancy by moving the `RawIrcMessage` property to `TwitchLibMessage`, which is the base class for both `ChatMessage` and `WhisperMessage`
=> move RawIrcMessage from ChatMessage to TwitchLibMessage

TwitchLib.Client.Models/ConnectionCredentials.cs, TwitchLib.Client/TwitchClient.cs
New model in ConnectionCredentials containing booleans for each of the supported capabilities.
Tested to ensure the default behavior is all three enabled, and also tested disabling each individual one, as well as all of them.
=> ability to disable individual capability requests

TwitchLib.Client.Models/ContinuedGiftedSubscription.cs, TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client.Models/Internal/Tags.cs, TwitchLib.Client/Events/OnContinuedGiftedSubscriptionArgs.cs, TwitchLib.Client/TwitchClient.cs
Twitch has an event where a user whos subscription was gifted to them chooses to continue the subscription by paying for it themselves. This is a "giftpaidupgrade" event type, but I named it "ContinuedGiftedSubscription" based on the message that shows up in chat.
TwitchLib message currently:
```
Unaccounted for: @badge-info=subscriber/11;badges=subscriber/9;color=#DAA520;display-name=Varanid;emotes=;flags=;id=a2d384c1-c30a-409e-8001-9e7d8f9c784d;login=varanid;mod=0;msg-id=giftpaidupgrade;msg-param-sender-login=cletusbueford;msg-param-sender-name=CletusBueford;room-id=44338537;subscriber=1;system-msg=Varanid\sis\scontinuing\sthe\sGift\sSub\sthey\sgot\sfrom\sCletusBueford!;tmi-sent-ts=1612497386372;user-id=67505836;user-type= :tmi.twitch.tv USERNOTICE #burkeblack (please create a TwitchLib …
```
=> Support for gifted subscriptions that get continued by the recipient

TwitchLib.Client/TwitchClient.cs
This issue was initially brought forward in #140  and then again in  #163 . Thanks @Felk for bringing attention to this.
The auto channel join queue was previously not populated with the currently joined channels when a reconnect occurs, meaning when the client reconnects to Twitch, it has no channels to automatically join, and the programmer has to write logic in `OnConnected` to rejoin them.
This should fix that problem.
Currently:
```
. . .
Finished channel joining queue.
Received: @badge-info=founder/80;badges=moderator/1,founder/0,bits/25000;client-nonce=15be6227cbda00046a1f955522bfa75c;color=#CC00C5;display-name=swiftyspiffy;emotes=;flags=;id=783279b9-952d-4fda-ac61-b92143c3c885;mod=1;room-id=44338537;subscriber=0;tmi-sent-ts=1613261977689;turbo=0;user-id=40876073;user-type=mod …
```
=> Repopulate the auto channel join queue on reconnects

TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
`TwitchLib.Communication`'s `Open()` method actually returns whether it succeeded or not. We should surface that result.
=> Return bool representing Connect() success

TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client.Models/PrimePaidSubscriber.cs, TwitchLib.Client/Events/OnPrimePaidSubscriberArgs.cs, TwitchLib.Client/TwitchClient.cs
This event fires when a subscriber to a channel upgrades from a Prime Gaming subscription to a paid subscription (any tier).
Tested against the following IRC string, and working:
```
@badge-info=subscriber/1;badges=subscriber/0,premium/1;color=;display-name=swiftyspiffy;emotes=;flags=;id=fd9f568c-325b-447f-aa03-e4dc08d661d5;login=swiftyspiffy;mod=1;msg-id=primepaidupgrade;msg-param-sub-plan=1000;room-id=44338537;subscriber=1;system-msg=swiftyspiffy\\sconverted\\sfrom\\sa\\sTwitch\\sPrime\\ssub\\sto\\sa\\sTier\\s1\\ssub!;tmi-sent-ts=1553627414793;user-id=40876073;user-type= :tmi.twitch.tv USERNOTICE #burkeblack
```
=> Support primepaidupgrade event

TwitchLib.Client.Models/Internal/Tags.cs
Twitch originally misspelled the tag in both their announcement and the documentation page,
but have fixed the mistake in the documentation by now, as can be inferred by this uservoice post:
https://twitch.uservoice.com/forums/310213-developers/suggestions/40811302-new-irc-tag-msg-params-gift-months-in-docs-is-ac
=> fix param multi month gift duration

TwitchLib.Client.Enums/TwitchLib.Client.Enums.csproj, TwitchLib.Client.Models/TwitchLib.Client.Models.csproj, TwitchLib.Client/TwitchLib.Client.csproj
Currently XML comments aren't included in the Nuget package and therefore don't show in the users intellisense.
This PR aims to include the comments to enable the users intellisense to support them with information they may need.
=> Include xml comments into nuget packages

TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client/Events/OnDuplicateArgs.cs, TwitchLib.Client/Events/OnRateLimitArgs.cs, TwitchLib.Client/TwitchClient.cs
This PR silently ignores capacity event messages, and adds support for eventing on rate limit and duplicate error messages from Twitch.
This is tested.
=> Handle capacity, rate limit, and duplicate events from Twitch

TwitchLib.Client.Models/Internal/IrcMessage.cs, TwitchLib.Client/TwitchClient.cs
353 irc messages are now parsed correctly.  The associated event (OnExistingUsersDetected) also fires as expected now. This issue was originally identified in 2019 by @Seeker1437 here: https://github.com/TwitchLib/TwitchLib/issues/436
Sample 353 message:
```
:swiftyspiffy.tmi.twitch.tv 353 swiftyspiffy = #burkeblack :jadrol mcober mr_perril naqeth bellolibr cjwprostar famousivan imshnaz limechaser neonenenderas noirmagic ruckinhell09 applessauces drunkennewbie knightofhamsters mrfancyrat nightleaf davethulhu ijustnt hostilebobcat kei_l limazulutango si_cwan strangedave streamelements ashbradford faps247 thetrufflebunny ussdefiant60 the_kraken_bot thenom mr_mio yvilion jollyman77 lordhh10 michael_angelo33 steelkreeg e2bm53 ikpeba
```
Tested and working. Also careful to apply this logic …
=> Fix IrcMessage parsing bug for (weird) 353 messages

TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client.Models/Internal/Tags.cs
The First Time Chatter notification in chat is indicated by the `first-msg` irc parameter of the ChatMessage model. This PR adds a `IsFirstMessage` property to ChatMessage that reflects this value.
Sample IRC:
```
@badge-info=;badges=;client-nonce=20e793408e1413f915ee6442553792c0;color=;display-name=swiftyspiffyv5;emotes=;first-msg=1;flags=;id=166f5981-70dd-4d0a-b3f0-0e663aafd568;mod=0;room-id=723565395;subscriber=0;tmi-sent-ts=1639867328596;turbo=0;user-id=187514468;user-type= :swiftyspiffyv5!swiftyspiffyv5@swiftyspiffyv5.tmi.twitch.tv PRIVMSG #chonkology :test
```
=> add IsFirstMessage property to ChatMessage model

TwitchLib.Client/TwitchClient.cs
While TwitchClient.Reconnect() currently joins all channels, it wont join all channel if the IClient only was reconencted. I moved adding the currently joined channel to the joining queue from Reconnect() to _client_OnReconnected() since the Reconnect() Methode calls the _client.Reconnect() methode which calls the _client_OnReconnected Event. To ensure that the BotAccount doesnt get joined twice, i check if it is not him and then add to the queue.
To get this work i need to remove the _joinedChannelManager.Clear() from _client_OnDisconnected since it gets deleted on the TwitchClient.Disconnect() Methode but stays if only the IClient gets disconnected to ensure it can be queued again after the reconnect.
=> Fixed joining Channel on IClient Reconnect()

TwitchLib.Client/TwitchClient.cs
There has been a lot of cases where users had trouble interacting with channels, simply because they were unaware that they shouldn't prepend a number sign when passing a channel as a parameter.
This PR aims to handle channel parameters prepended with a number sign, since this is not a consistent case with every Twitch library out there, I thought it would help if both cases were accounted for.
=> 'channel' parameters in TwitchClient methods to handle channels starting with number sign (#)

TwitchLib.Client.Models/ChannelState.cs
Fixes a small typo of a comment in ChannelState.cs ['assignedc' > 'assigned'](https://github.com/TwitchLib/TwitchLib.Client/blob/master/TwitchLib.Client.Models/ChannelState.cs#L31).
=> Fixes a comment typo in ChannelState.cs

TwitchLib.Client/TwitchClient.cs
If the 'channel' parameter is null in the TwitchClient::Initialize method, the application will crash with a NullReferenceException. This is due to a recently added check in https://github.com/TwitchLib/TwitchLib.Client/pull/201 . This does not seem intended as the default value for channel is null, hence this quick check.
=> Add null check to TwitchClient::Initialize

TwitchLib.Client/TwitchClient.cs
TwitchLib currently logs everything with the 'Information' level, which is HORRIBLE for anyone adding a logger. Not only does it blast you with logs that are (99% of the time) useless, but it also makes it impossible to see what you're logging in your actual code.
Any channel that averages 100+ viewers will have your console looking like this: 
Every few seconds as membership joins are received from IRC your console will be filled with these logs, hiding anything useful that you would want to see.
This PR aims to address this issue, by logging things with their relevant levels; I have added an additional optional parameter to the Log() method, which allows setting the logging level.
=> Tweak logging to have logical levels instead of logging everything as Information.

TwitchLib.Client/TwitchClient.cs
Before:
```
var client = new TwitchLib.Client.TwitchClient();
client.Initialize(new ConnectionCredentials("swiftyspiffy", "asdasdasd"), "swiftyspiffy");
client.Connect();
client.OnIncorrectLogin += (sender, loginArgs) =>
{
Console.WriteLine("Failed to login!");
};
```
```
LOG: Joining channel: swiftyspiffy
LOG: Received: :tmi.twitch.tv NOTICE * :Login authentication failed
LOG: Unaccounted for: :tmi.twitch.tv NOTICE * :Login authentication failed (please create a TwitchLib GitHub issue :P)
```
After:
```
var client = new TwitchLib.Client.TwitchClient();
client.Initialize(new ConnectionCredentials("swiftyspiffy", "asdasdasd"), "swiftyspiffy");
client.Connect();
client.OnIncorrectLogin += (sender, loginArgs) =>
{
Console.WriteLine("Failed to login!");
};
```
```
LOG: Joining channel: …
```
=> fix: OnIncorrectLogin now correctly detects login authentication failed

TwitchLib.Client.Models/Builders/ConnectionCredentialsBuilder.cs, TwitchLib.Client.Models/ConnectionCredentials.cs, TwitchLib.Client/Extensions/LogExtensions.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/Throttling/ThrottlingService.cs, TwitchLib.Client/TwitchClient.cs, TwitchLib.Client/TwitchLib.Client.csproj
- Better logging
- removed unused property `TwitchWebsocketURI`
- `TwitchClient` now accepts `ILoggerFactory` instead of `ILogger<TwitchClient>` so logging for `TcpClient`/`WebSocketClient` is now enabled by default
=> improve logging performance

TwitchLib.Client/TwitchClient.cs
The Twitch handshake on the reconnect was missing. Because of that, Twitch closed the connection to the client resulting in being unable to reconnect. Also the joining of the channels was missing.
Since the TwitchUsername (from the Credentials) isn't automatically joined, it doesn't need to check whether the channel is not the TwitchUsername.
=> Missing handshake and joining channel on reconnect fix

TwitchLib.Client.Benchmark/ChatMessage.cs, TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client.Models/Internal/IrcMessage.cs, TwitchLib.Client.Models/MessageEmote.cs, TwitchLib.Client/Events/OnExistingUsersDetectedArgs.cs, TwitchLib.Client/Events/OnVIPsReceivedArgs.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs, TwitchLib.Client/Extensions/SplitExtensions.cs, TwitchLib.Client/Internal/Parsing/IrcParser.cs, TwitchLib.Client/TwitchClient.cs
- Fix a bug in HandleNotice where `UnaccountedFor(...)` fallback was called even when `OnUnaccountedFor` event had a handler
- Fix comment on `IrcMessage` ctor
- Fix bug in `MesageEmoteCollection.Add(...)` which was indefinitely pattern + emoteText concatenating replacement regex until running out of maximum string length and crashing the application
- Fix usage of `SortedList` in `MessageEmoteCollection` - replaced with `Dictionary`
- Fix missed slicing in IrcParser to remove `@` at the start of tag sequence
- Fallback to unaccounted for on failed login if no failed login handler is registered (previously it would have been silently ignored)
- Rewrite `HandleIrcMessageAsync` to use switch expression and forward the task
- Simplify and clean up `HandlePrivMsg`
- Rewrite `HandleNotice` to …
=> Fix `MessageEmoteCollection` + additional fixes/improvements

TwitchLib.Client.Models/Common/Helpers.cs, TwitchLib.Client.Models/EmoteSet.cs, TwitchLib.Client.Models/Extensions/SpanSliceEnumerator.cs, TwitchLib.Client.Models/Extractors/EmoteExtractor.cs, TwitchLib.Client.Models/TwitchLib.Client.Models.csproj
Before:
| Method |               badges |     Mean |   Error |  StdDev |   Gen0 | Allocated |
|------- |--------------------- |---------:|--------:|--------:|-------:|----------:|
|    One |        subscriber/12 | 101.9 ns | 1.97 ns | 2.89 ns | 0.0484 |     304 B |
|    Two| subsc(...)ter/1 [27] | 188.6 ns | 2.58 ns | 3.86 ns | 0.0980 |     616 B |
|  theree | subsc(...)rbo/1 [35] | 235.9 ns | 2.42 ns | 3.47 ns | 0.1259 |     792 B |
|   Four| subsc(...)dsa/1 [47] | 293.8 ns | 3.04 ns | 4.55 ns | 0.1564 |     984 B |
After:
| Method |               badges |      Mean |    Error |   StdDev |   Gen0 | Allocated |
|------- |--------------------- |----------:|---------:|---------:|-------:|----------:|
|    One |        subscriber/12 |  87.95 ns | 2.353 ns | 3.299 ns | 0.0370 |     232 B |
| …
=> faster/efficient `EmoteExtractor` and `Helpers`

TwitchLib.Client.Models/Internal/IrcMessage.cs, TwitchLib.Client.Test/TwitchClientEventTests.cs
Fixes NREs thrown around ChatMessage ctor and message handlers. This was not commonly hit previously because IrcParser used to always set the dictionary even if the message did not have any tags, despite the fact that IrcMessage's constructors exposed `tags` as optional argument that defaults to null - fix that by doing `??= new Dict...` because all code in TwitchLib assumes that the tags are never null.
=> Make sure IrcMessage.Tags is never null and devirtualize the dictionary because it is used in hot paths

TwitchLib.Client/TwitchClient.cs
- Don't return on the first line, process all lines
~~- Queue event handling concurrently (the sync part will run inline until the first yield)~~ Will refactor to channels in a separate PR.
Whoops, sorry.
=> Fix _client_OnMessage handling

TwitchLib.Client.Models/MessageEmote.cs
- adds support for 7tv emotes (joins bttv and ffz)
- adds a hack that fixes the emote replaced string that's been broken for like 5 years
- this was originally referenced in #21 . the codebase for this feature is actually... quite complex. this hack changes the generated regex match string to require either space on one side or both sides, which is effectively the rules Twitch uses
- LUL DansGame "LUL"
```
https://static-cdn.jtvnw.net/emoticons/v1/425618/1.0 https://static-cdn.jtvnw.net/emoticons/v1/33/1.0 "LUL"
```
- LUL DansGame "LUL" LUL LUL "LUL" "DansGame" WutFace "WutFace" MrDestructoid MrDestructoid
```
https://static-cdn.jtvnw.net/emoticons/v1/425618/1.0 https://static-cdn.jtvnw.net/emoticons/v1/33/1.0 "LUL" https://static-cdn.jtvnw.net/emoticons/v1/425618/1.0 …
```
=> MessageEmote: fixes emote replaced string with a hack until this can be re-written to something more sane, adds support for 7tv emotes

TwitchLib.Client.Benchmark/ChatMessage.cs, TwitchLib.Client.Benchmark/IrcMessageHandler.cs, TwitchLib.Client.Benchmark/IrcParser.cs, TwitchLib.Client.Benchmark/TwitchLib.Client.Benchmark.csproj, TwitchLib.Client.Models/Internal/IrcMessage.cs, TwitchLib.Client/Extensions/SplitExtensions.cs, TwitchLib.Client/Parsing/IrcParser.cs, TwitchLib.Client/TwitchClient.cs
Supersedes #217
We can now make `IrcParser` public and it will do the right thing (tm) when utilized from user code.
- Add missing doc comments
- Add null/short string guard
- Improve parser perf. by another up to 15% depending on runtime by improving SplitFirst/Last logic (adopting learnings from working on another project)
To be honest, it is pretty meaningless to continue improving parsing performance since `TwitchLib` impl. is now faster than *popular* alternatives in Java, Rust and Go (some of them kind of shoot themselves in the foot though). But hey, neuron activation.
(before version supposedly roll-forwarded to a newer compiler version too so runtime perf. differences should not be significant)
Before:
```
BenchmarkDotNet=v0.13.5, OS=macOS 14.0 [Darwin 23.0.0]
Apple M1 Pro, 1 …
```
=> IrcParser: make public and speed up by another <=15%

TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs, TwitchLib.Client/TwitchLib.Client.csproj
* Updated underlaying Communication library to stable version 2.0.0
* Removed sync overloads for `SendReply` and `SendQueuedItem`
=> Update communication lib

TwitchLib.Client.Models/Extractors/EmoteExtractor.cs, TwitchLib.Client.Test/Parsing.cs
Fixes https://github.com/TwitchLib/TwitchLib.Client/issues/259
=> Update EmoteExtractor to support multibyte

TwitchLib.Client.Models/ConnectionCredentials.cs
If no username is provided to the ConnectionCredentials, a default username of `justinfan` right-padded with 4-5 random digits will be generated which will allow an anonymous connection to twitch.
This follows the same logic used by [tmi.js](https://github.com/tmijs/tmi.js/blob/main/lib/utils.js#L27).
=> Updated ConnectionCredentials to use an anonymous user by default

TwitchLib.Client.Models/GiftedSubscription.cs, TwitchLib.Client.Models/Internal/Tags.cs
This PR adds support for MsgParamOriginId to the GiftedSubscription model. 
`
@badge-info=founder/122;badges=staff/1,moderator/1,founder/0,sub-gifter/300;color=#FF3AE9;display-name=swiftyspiffy;emotes=;flags=;id=26dd4088-9efb-49bf-8fcc-32d04d530bd3;login=swiftyspiffy;mod=1;msg-id=subgift;msg-param-gift-months=1;msg-param-goal-contribution-type=SUB_POINTS;msg-param-goal-current-contributions=2749;msg-param-goal-target-contributions=2600;msg-param-goal-user-contributions=1;msg-param-months=78;msg-param-origin-id=17946483715777061145;msg-param-recipient-display-name=BleuBelladonna;msg-param-recipient-id=75543494;msg-param-recipient-user-name=bleubelladonna;msg-param-sender-count=310;msg-param-sub-plan-name=The\sPirate's\sSubscription;msg-param-sub-plan=1000;room-id=44338537;subscriber=1;syste …
=> adds MsgParamOriginId to GiftedSubscription model
