TwitchLib.Client/TwitchLib.Client.csproj
Update NuGet pacakges and version number
=> Final for v2 by S7evin

TwitchLib.Client/Models/OutboundChatMessage.cs, TwitchLib.Client/Models/OutboundWhisperMessage.cs, TwitchLib.Client/TwitchClient.cs
Added a couple classes to handle Outbound Whispers/Messages.  Also removed redundant checks in SendMessage()
=> Small readability improvements

TwitchLib.Client/Models/GiftedSubscription.cs
=> MsgParamSubPlan is now an enum, consistent with the SubscriptionBase

README.md
Added reference to main readme.
=> Added reference to main readme.

TwitchLib.Client/Manager/JoinedChannelManager.cs, TwitchLib.Client/Models/BeingHostedNotification.cs, TwitchLib.Client/Models/ChannelState.cs, TwitchLib.Client/Models/ChatCommand.cs, TwitchLib.Client/Models/ChatMessage.cs, TwitchLib.Client/Models/ConnectionCredentials.cs, TwitchLib.Client/Models/ErrorEvent.cs, TwitchLib.Client/Models/GiftedSubscription.cs, TwitchLib.Client/Models/JoinedChannel.cs, TwitchLib.Client/Models/OutboundChatMessage.cs, TwitchLib.Client/Models/OutgoingMessage.cs, TwitchLib.Client/Models/RitualNewChatter.cs, TwitchLib.Client/Models/SentMessage.cs, TwitchLib.Client/Models/SubscriberBase.cs, TwitchLib.Client/Models/UserBan.cs, TwitchLib.Client/Models/UserState.cs, TwitchLib.Client/Models/UserTimeout.cs, TwitchLib.Client/Models/WhisperCommand.cs, TwitchLib.Client/Models/WhisperMessage.cs, TwitchLib.Client/TwitchClient.cs
=> Sets passed in channel to lowercase when sending join command.

TwitchLib.Client/TwitchClient.cs
Temp fix proposal for OnDisconnected Event Multi fire
=> Temp fix proposal for OnDisconnected Event Multi fire

TwitchLib.Client.Models/ConnectionCredentials.cs, TwitchLib.Client/TwitchClient.cs
- Removed TwitchHost, TwitchPort
- Added TwitchWebsocketURI
- Defaults to wss/443 now, instead of ws/80
=> Simplifies ConnectionCredentials, defaults values to use SSL

TwitchLib.Client.Models/ConnectionCredentials.cs, TwitchLib.Client/Interfaces/ITwitchWebSocket.cs, TwitchLib.Client/TwitchClient.cs
- Removes ability to easily tunnel connection through proxy.
=> Proxy Support Removal

TwitchLib.Client/Extensions/MarkerExt.cs
- Adds extension to use Marker
=> Marker support

TwitchLib.Client.Test/MockIClient.cs, TwitchLib.Client.Test/TwitchClientEventTests.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
There is no need to dispose the client.
=> Reconnect Twitchclient using internal reconnect method

TwitchLib.Client.Models/CommunitySubscription.cs, TwitchLib.Client.Models/GiftedSubscription.cs
=> Adds UserId to community sub and gifted sub

TwitchLib.Client/Extensions/TimeoutUserExt.cs
Avoids issues with sub-second or negative durations. Closes #76
=> add timeout duration validation

TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client/TwitchClient.cs
Reverts TwitchLib/TwitchLib.Client#82
Needs to be merged to dev
=> Revert "Fixed a bug with OnModeratorsReceived"

TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client/Events/OnVIPsReceivedArgs.cs, TwitchLib.Client/Extensions/VipExt.cs, TwitchLib.Client/TwitchClient.cs
- Adds VIP extension with:
- VIP(): Add new VIP
- UnVIP(): Removes VIP
- GetVIPs(): Ask Twitch for list of VIPs
- Adds OnVIPsReceived event housing channel and all VIPs in channel
Test against channel without VIPs enabled, without VIPs, and with VIPs
=> Adds VIP, UnVIP, and GetVIPs in VIP extension, and OnVIPsReceived event

TwitchLib.Client.Enums/Internal/IrcCommand.cs, TwitchLib.Client/Events/OnMessageClearedArgs.cs, TwitchLib.Client/Internal/Parsing/IrcParser.cs, TwitchLib.Client/TwitchClient.cs
- Adds newly supported IRC command `ClearMsg` (`CLEARMSG`)
- Adds new event for detecting when a message is removed from chat called `OnMessageCleared`
Tested.
=> Support for detecting removed messages

TwitchLib.Client.Models/UserState.cs
=> Fix problem with initialization

TwitchLib.Client.Models/UserState.cs
Reverts TwitchLib/TwitchLib.Client#105
=> Revert "Fix problem with initialization"

TwitchLib.Client/Events/OnMessageClearedArgs.cs, TwitchLib.Client/TwitchClient.cs
- Adds TmiSentTs to OnMessageCleared
- Fixes TargetMessageId in OnMessageCleared
=> fixes OnMessageCleared TargetMessageId, adds TmiSentTs

TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
Per guidance here: https://help.twitch.tv/s/article/rooms-are-closing?language=en_US
Room support was removed as October 30th.
=> remove Rooms support

TwitchLib.Client.Models/ChatMessage.cs
Founder badge is now compatible with IsSubscribed and SubscribedMonthCount. Issue: #129
=> Founder badge is now compatible with IsSubscribed and SubscribedMonthCount

TwitchLib.Client.Models/ChatMessage.cs
As requested in #130 , this adds IsVIP to the ChatMessage model.
=> Adds support for IsVIP in ChatMessage model

TwitchLib.Client/Extensions/DeleteMessageExt.cs
- `DeleteMessage(this ITwitchClient client, JoinedChannel channel, string messageId)`
- `DeleteMessage(this ITwitchClient client, string channel, string messageId)`
- `DeleteMessage(this ITwitchClient client, string channel, string messageId)`
- `DeleteMessage(this ITwitchClient client, string channel, ChatMessage msg)`
=> add delete command extension

TwitchLib.Client.Models/Builders/ChatMessageBuilder.cs, TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs
Maybe this is a short but useful addition to ChatMessages. I just added IsStaff and IsPartner to ChatMessages based on the Badges and UserType
=> Add IsStaff and IsPartner to ChatMessage

TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client/Events/OnRequiresVerifiedEmailArgs.cs, TwitchLib.Client/Events/OnRequiresVerifiedPhoneNumberArgs.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
NOTE: these are only send as a failure message if trying to send messages without meeting requirements
=> Added message handling for required email and phone verification NOTICES

TwitchLib.Client.Enums/TwitchLib.Client.Enums.csproj, TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client.Models/TwitchLib.Client.Models.csproj, TwitchLib.Client/Events/OnBadHostErrorArgs.cs, TwitchLib.Client/Events/OnBadHostRateExceededArgs.cs, TwitchLib.Client/Events/OnBadUnhostErrorArgs.cs, TwitchLib.Client/Events/OnBannedArgs.cs, TwitchLib.Client/Events/OnEmoteOnlyArgs.cs, TwitchLib.Client/Events/OnFollowersOnlyArgs.cs, TwitchLib.Client/Events/OnHostTargetWentOfflineArgs.cs, TwitchLib.Client/Events/OnR9kModeArgs.cs, TwitchLib.Client/Events/OnSlowModeArgs.cs, TwitchLib.Client/Events/OnSubsOnlyArgs.cs, TwitchLib.Client/Events/OnSuspendedArgs.cs, TwitchLib.Client/TwitchClient.cs, TwitchLib.Client/TwitchLib.Client.csproj
- OnFollowersOnly
- OnSubsOnly
- OnEmoteOnly
- OnSuspended
- OnBanned
- OnSlowMode
- OnBadHostError
- OnBadUnhostError
- OnBadHostRateExceeded
- OnHostTargetWentOffline
=> Add a bunch of new supported events

TwitchLib.Client.Models/Announcement.cs, TwitchLib.Client.Models/Internal/MsgIds.cs, TwitchLib.Client.Models/Internal/Tags.cs, TwitchLib.Client/Events/OnAnnouncementArgs.cs, TwitchLib.Client/Extensions/AnnoucementExt.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs, TwitchLib.Client/TwitchLib.Client.csproj
- Adds support to create announcements via a TwitchClient extension method
- Adds support for announcement usernotices via the OnAnnouncement event
- updated communication nuget to non-prerelease to prepare for a proper full release
=> Add Announcements feature

TwitchLib.Client/TwitchClient.cs
https://github.com/TwitchLib/TwitchLib.Client/issues/187
https://github.com/TwitchLib/TwitchLib/issues/1090
=> return after invoking OnIncorrectLogin event to prevent unaccounted for logging

TwitchLib.Client.Models/Builders/UserStateBuilder.cs, TwitchLib.Client.Models/UserState.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs
Squished commits to 3 from previous PR errors
=> Userstate Update

TwitchLib.Client.Models/Builders/UserTimeoutBuilder.cs, TwitchLib.Client.Models/UserTimeout.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs
https://github.com/TwitchLib/TwitchLib/issues/1098
=> Add Target User ID to timeout event

TwitchLib.Client.Enums/TwitchLib.Client.Enums.csproj, TwitchLib.Client.Models/TwitchLib.Client.Models.csproj, TwitchLib.Client/TwitchLib.Client.csproj
Changelog:
- Fixed a NRE if channel is null in Intialize (the default value)
=> [Release] Version 3.3.1

TwitchLib.Client/Extensions/AnnoucementExt.cs, TwitchLib.Client/Extensions/BanUserExt.cs, TwitchLib.Client/Extensions/ChangeChatColorExt.cs, TwitchLib.Client/Extensions/ClearChatExt.cs, TwitchLib.Client/Extensions/CommercialExt.cs, TwitchLib.Client/Extensions/DeleteMessageExt.cs, TwitchLib.Client/Extensions/EmoteOnlyExt.cs, TwitchLib.Client/Extensions/FollowersOnlyExt.cs, TwitchLib.Client/Extensions/GetChannelModeratorsExt.cs, TwitchLib.Client/Extensions/MarkerExt.cs, TwitchLib.Client/Extensions/ModExt.cs, TwitchLib.Client/Extensions/RaidExt.cs, TwitchLib.Client/Extensions/ReplyWhisperExt.cs, TwitchLib.Client/Extensions/SlowModeExt.cs, TwitchLib.Client/Extensions/SubscribersOnly.cs, TwitchLib.Client/Extensions/TimeoutUserExt.cs, TwitchLib.Client/Extensions/UnbanUserExt.cs, TwitchLib.Client/Extensions/VipExt.cs, TwitchLib.Client/TwitchClient.cs
https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486
=> Deprecate chat commands

TwitchLib.Client.Models/Interfaces/ISendOptions.cs, TwitchLib.Client.Models/SendOptions.cs, TwitchLib.Client.Models/TwitchLib.Client.Models.csproj, TwitchLib.Client.Test/ThrottlingServiceTests.cs, TwitchLib.Client.Test/TwitchClientEventTests.cs, TwitchLib.Client.Test/TwitchLib.Client.Test.csproj, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/Internal/EventHelper.cs, TwitchLib.Client/Throttling/Throttler.cs, TwitchLib.Client/Throttling/ThrottlingService.cs, TwitchLib.Client/TwitchClient.cs, TwitchLib.Client/TwitchLib.Client.csproj
* Reimplemented message throttling
* Added send options
* Abstracted event raising
* Added some more tests
=> Reimplemented message throttling

.github/workflows/check-buildstatus.yml, TwitchLib.Client.Models/Extensions/NetCore/ColorTranslator.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/TwitchClient.cs
fix #215 
fix name in check-buildstatus.yml
expose private (chat/whisper)CommandIdentifiers instead of methods
=> fix #215 and expose (chat/whisper)CommandIdentifiers

TwitchLib.Client/Events/OnModeratorsReceivedArgs.cs, TwitchLib.Client/Events/OnRaidedChannelIsMatureAudienceArgs.cs, TwitchLib.Client/Events/OnVIPsReceivedArgs.cs, TwitchLib.Client/Extensions/EventInvocationExt.cs, TwitchLib.Client/Interfaces/ITwitchClient.cs, TwitchLib.Client/OnNoPermissionErrorArgs.cs, TwitchLib.Client/OnSelfRaidErrorArgs.cs, TwitchLib.Client/TwitchClient.cs
- Fixes perf regression vs master by no longer having to dispatch running their handlers via Task.Run (it's partially my fault though)
- Adds corresponding rich event args
I think just command + message is enough, let me know if these events were left intentionally sync or their args need adjustment.
=> Make the last 3 events async

TwitchLib.Client.Models/ChatMessage.cs, TwitchLib.Client.Models/ChatReply.cs, TwitchLib.Client.Models/Internal/Tags.cs
[Changes:](https://dev.twitch.tv/docs/change-log/#:~:text=2023%E2%80%9108%E2%80%9104)
- new `Chat Reply` properties
- updated doc
=> Changelog 2023‑08‑04

TwitchLib.Client.Models/MessageEmote.cs
nullable annotation
small optimization
=> nullable annotation for `MessageEmote.cs`

TwitchLib.Client.Test/Parsing.cs
Improves the EmoteExtractor test to confirm the Index is as expected also
=> Improve EmoteExtractor test
